<?php
/**
 * Created by PhpStorm.
 * User: finleysiebert
 * Date: 12-02-18
 * Time: 17:44
 */

namespace App\Controller;
use App\Model\Table\PostsTable;
use Cake\Event\Event;


/**
 * @property PostsTable Posts
 */
class PostsController extends AppController
{
    public function beforeFilter(Event $event)
    {
        $this->Auth->allow(['index']);
        return parent::beforeFilter($event); // TODO: Change the autogenerated stub
    }

    public function index() {

        $posts = $this->Posts->find('all');


        $this->set(compact(['posts']));
    }
}